### ISSUE TITLE
Design a new ECF website

### ISSUE THREAD

**Issue by andytudhope** [status-im/ECF#1]
## ECF description 
Blockchains, crypto-assets, and decentralized applications are the most transformative innovations of our generation. While poised for substantial growth over the coming years, mainstream adoption remains at an early stage, and the appropriate public infrastructure to support billions of users is still a matter of deep R&D. The aim of the Ethereum Community Fund (ECF) is to provide both funding and connectivity, while shaping the strategic direction of the space towards mainstream adoption through the development of infrastructure and compelling end-user applications.

The idea is to have one landing page, linking to different elements. This is a bounty to design that landing page.

Right now this is what we have: https://ecf.network/

We like the design here: http://ethprize.io/ and would be looking to use similar, simple, clean elements,  similar colour scheme, and some nice animations. 

If you want to design the site, let us know in the comments below, along with a reference to your past and present work and once we have settled on a designer we will 'lock' the bounty and accept no more submissions.

## About
This copy, for now, stays the same as the landing page
The logos of the projects would have to be incorporated in a nicer way (and updated).
More info on the logo will be provided to the designer chosen.

## Contact
General questions: Standard contact form
Press enquiries: press@ecf.network

## Apply
Applications via form button: https://docs.google.com/forms/d/e/1FAIpQLSdeH8g4yAJQXxYzLpUlhksA72nb2Z0Fy2Kwc2h7mpas3Al02g/viewform

## Links: 
Medium link: https://medium.com/ecf-review
Github: https://github.com/EthereumCommunityFund
Twitter: https://twitter.com/ethereumecf

## Wireframe
<img width="1013" alt="screen shot 2018-05-17 at 13 09 27" src="https://user-images.githubusercontent.com/13001517/40192826-539b020c-59ba-11e8-8f78-f0fa72354566.png">

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x15299cbd6e8a324844fff6711676eb13c00126173df5e3a0647f8c1e6d52401f](https://etherscan.io/tx/0x15299cbd6e8a324844fff6711676eb13c00126173df5e3a0647f8c1e6d52401f)

**Comment by andytudhope** [comment]
cc @denis-sharypin @fshkliarau @qnou if you want to work on this/would know some people capable of handling it. The bounty will be funded shortly, just sorting out final details there.

**Comment by andytudhope** [comment]
Here are the logo and other designs so far, to give you a template/suggestion to work off.  
  

![ecf_logo_white on dark](https://user-images.githubusercontent.com/13001517/40193990-d1b0f504-59bd-11e8-974f-28b628761694.jpg)
![ecf_logo_black on white](https://user-images.githubusercontent.com/13001517/40194033-ef370384-59bd-11e8-853c-a9d28428b27c.jpg)
![ecf_element_darkbg_logo](https://user-images.githubusercontent.com/13001517/40193997-d4f5a868-59bd-11e8-9674-e0320f0e54a4.jpg)
![ecf_element_whitebg_logo](https://user-images.githubusercontent.com/13001517/40193995-d39c4d8c-59bd-11e8-9fed-32aa6acefc97.jpg)

**Comment by qnou** [comment]
Love what ecf is doing and have the capacity to get it done. Let me know @andytudhope.

**Comment by andytudhope** [comment]
Amazing @qnou - then we can lock this bounty for you and move forward because we already know how much you rock. Will start an email thread with Maria and Cassandra.

**Comment by cassshih** [comment]
Can't believe how fast we got an amazing designer through the bounty program. Thank you so much @andytudhope, @qnou, and MP!

**Comment by qnou** [comment]
@cassshih community support begets community support. 🙂

**Comment by andytudhope** [comment]
This bounty is now locked for qnou. Thank you ❤️

**Comment by debragail** [comment]
very nice design @qnou

**Comment by faizalsb** [comment]
Is this bounty still available? I'm interested

**Comment by andytudhope** [comment]
No, this bounty is closed, sorry @faizalsb
